export type Official = {
  name: string;
  jabatan: string;
  category: string;
};

export const OFFICIALS = [
    { name: "APRIYANTI", jabatan: "STAF SEKSI KESEJAHTERAAN", category: "Pemerintah Desa" },
    { name: "DARSUM DARJO", jabatan: "KEPALA DUSUN RUNGKANG", category: "Pemerintah Desa" },
    { name: "HERU WAHYONO", jabatan: "SEKRETARIS DESA", category: "Pemerintah Desa" },
    { name: "KARYO", jabatan: "KEPALA DUSUN MARGASARI", category: "Pemerintah Desa" },
    { name: "KASIRIN", jabatan: "STAF URUSAN UMUM DAN PERENCANAAN", category: "Pemerintah Desa" },
    { name: "MA,MUN", jabatan: "STAF SEKSI PELAYANAN", category: "Pemerintah Desa" },
    { name: "ROSIDI", jabatan: "STAF SEKSI PEMERINTAHAN", category: "Pemerintah Desa" },
    { name: "SAMSI", jabatan: "KEPALA SEKSI PELAYANAN", category: "Pemerintah Desa" },
    { name: "SARKUM SARTONO", jabatan: "KAUR UMUM DAN PERENCANAAN", category: "Pemerintah Desa" },
    { name: "SARYOKO", jabatan: "KAUR KEUANGAN", category: "Pemerintah Desa" },
    { name: "SURYATI", jabatan: "STAF URUSAN KEUANGAN", category: "Pemerintah Desa" },
    { name: "SUSANTO", jabatan: "KEPALA DESA", category: "Pemerintah Desa" },
    { name: "TEDY TRISNANTO", jabatan: "KEPALA SEKSI KESEJAHTERAAN", category: "Pemerintah Desa" },
    { name: "WAGINO", jabatan: "KEPALA SEKSI PEMERINTAHAN", category: "Pemerintah Desa" },
    { name: "ANDRI", jabatan: "KETUA RT 05 / RW 02", category: "RT/RW" },
    { name: "ARMAN", jabatan: "KETUA RT 06 / RW 01", category: "RT/RW" },
    { name: "DARMANTO", jabatan: "KETUA RT 03 / RW 02", category: "RT/RW" },
    { name: "DASILAM", jabatan: "KETUA RT 02 / RW 01", category: "RT/RW" },
    { name: "DIKIN", jabatan: "KETUA RT 01 / RW 01", category: "RT/RW" },
    { name: "DULAH YUSRI", jabatan: "KETUA RW 03", category: "RT/RW" },
    { name: "JUMONO", jabatan: "KETUA RT 07 / RW 01", category: "RT/RW" },
    { name: "KARTIM", jabatan: "KETUA RT 04 / RW 02", category: "RT/RW" },
    { name: "KASMAD", jabatan: "KETUA RW 01", category: "RT/RW" },
    { name: "KASMAD", jabatan: "KETUA RW 02", category: "RT/RW" },
    { name: "KUSNANTO", jabatan: "KETUA RT 01 / RW 02", category: "RT/RW" },
    { name: "MARDIYONO", jabatan: "KETUA RT 07 / RW 02", category: "RT/RW" },
    { name: "MULYADIHARJO", jabatan: "KETUA RT 03 / RW 01", category: "RT/RW" },
    { name: "MUSLIM", jabatan: "KETUA RT 06 / RW 02", category: "RT/RW" },
    { name: "NYAMAN SASTRO", jabatan: "KETUA RT 01 / RW 03", category: "RT/RW" },
    { name: "RASUM SUWENDI", jabatan: "KETUA RT 08 / RW 02", category: "RT/RW" },
    { name: "ROCHYADI", jabatan: "KETUA RT 09 / RW 02", category: "RT/RW" },
    { name: "SALIYO SUHANA", jabatan: "KETUA RT 03 / RW 03", category: "RT/RW" },
    { name: "SARIM SUNARTO", jabatan: "KETUA RT 05 / RW 01", category: "RT/RW" },
    { name: "SISWANTO", jabatan: "KETUA RT 04 / RW 01", category: "RT/RW" },
    { name: "SUTIJO", jabatan: "KETUA RT 02 / RW 03", category: "RT/RW" },
    { name: "SUTIKNO SUWANDI", jabatan: "KETUA RT 02 / RW 02", category: "RT/RW" },
    { name: "WASTAJA", jabatan: "KETUA RT 04 / RW 03", category: "RT/RW" },
    { name: "Aminah", jabatan: "Sari Rahayu 2", category: "Kader" },
    { name: "Apriyanti", jabatan: "Sari Rahayu 1", category: "Kader" },
    { name: "Dwiyantini", jabatan: "Sari Rahayu 3", category: "Kader" },
    { name: "Kamtiyah", jabatan: "Sari Rahayu 1", category: "Kader" },
    { name: "Kusmiyati", jabatan: "Sari Rahayu 1", category: "Kader" },
    { name: "Kusriyah", jabatan: "Sari Rahayu 3", category: "Kader" },
    { name: "Napsiyah", jabatan: "Sari Rahayu 2", category: "Kader" },
    { name: "Nurhayati", jabatan: "Sari Rahayu 3", category: "Kader" },
    { name: "Sulastri", jabatan: "Sari Rahayu 2", category: "Kader" },
    { name: "Supriyati", jabatan: "Sari Rahayu 3", category: "Kader" },
    { name: "Suryati", jabatan: "Sari Rahayu 1", category: "Kader" },
    { name: "Suwartiningsih", jabatan: "Sari Rahayu 1", category: "Kader" },
    { name: "Tati Romlah", jabatan: "Sari Rahayu 3", category: "Kader" },
    { name: "Yulitasari", jabatan: "Sari Rahayu 2", category: "Kader" },
    { name: "Yuni Ekowati", jabatan: "Sari Rahayu 2", category: "Kader" },
    { name: "Aminah", jabatan: "Sari Rahayu 2", category: "Karang Taruna" },
    { name: "Apriyanti", jabatan: "Sari Rahayu 1", category: "Karang Taruna" },
    { name: "Dwiyantini", jabatan: "Sari Rahayu 3", category: "Karang Taruna" },
    { name: "Kamtiyah", jabatan: "Sari Rahayu 1", category: "Karang Taruna" },
    { name: "Kusmiyati", jabatan: "Sari Rahayu 1", category: "Karang Taruna" },
    { name: "Kusriyah", jabatan: "Sari Rahayu 3", category: "Karang Taruna" },
    { name: "Napsiyah", jabatan: "Sari Rahayu 2", category: "Karang Taruna" },
    { name: "Nurhayati", jabatan: "Sari Rahayu 3", category: "Karang Taruna" },
    { name: "Sulastri", jabatan: "Sari Rahayu 2", category: "Karang Taruna" },
    { name: "Supriyati", jabatan: "Sari Rahayu 3", category: "Karang Taruna" },
    { name: "Suryati", jabatan: "Sari Rahayu 1", category: "Karang Taruna" },
    { name: "Suwartiningsih", jabatan: "Sari Rahayu 1", category: "Karang Taruna" },
    { name: "Tati Romlah", jabatan: "Sari Rahayu 3", category: "Karang Taruna" },
    { name: "Yulitasari", jabatan: "Sari Rahayu 2", category: "Karang Taruna" },
    { name: "Yuni Ekowati", jabatan: "Sari Rahayu 2", category: "Karang Taruna" },
    { name: "SITI AMINAH", jabatan: "KADER PEMBANGUNAN MANUSIA", category: "KPM" }
];

export const SILTAP_DATA = [
    { name: "SUSANTO", jabatan: "KEPALA DESA", amount: 3000000 },
    { name: "HERU WAHYONO", jabatan: "SEKRETARIS DESA", amount: 2500000 },
    { name: "SARKUM SARTONO", jabatan: "KAUR UMUM & PERENCANAAN", amount: 2200000 },
    { name: "SARYOKO", jabatan: "KAUR KEUANGAN", amount: 2200000 },
    { name: "WAGINO", jabatan: "KASI PEMERINTAHAN", amount: 2200000 },
    { name: "SAMSI", jabatan: "KASI PELAYANAN", amount: 2200000 },
    { name: "TEDY TRISNANTO", jabatan: "KASI KESEJAHTERAAN", amount: 2200000 },
    { name: "DARSUM DARJO", jabatan: "KEPALA DUSUN RUNGKANG", amount: 2100000 },
    { name: "KARYO", jabatan: "KEPALA DUSUN MARGASARI", amount: 2100000 },
];

export const BPD_INSENTIF_DATA = [
    { name: "ANWAR SIDIK", jabatan: "KETUA BPD", amount: 1000000 },
    { name: "PONIMAN", jabatan: "WAKIL KETUA BPD", amount: 800000 },
    { name: "SITI MAESAROH", jabatan: "SEKRETARIS BPD", amount: 700000 },
    { name: "SARYONO", jabatan: "ANGGOTA BPD", amount: 600000 },
    { name: "SUTRISNO", jabatan: "ANGGOTA BPD", amount: 600000 },
    { name: "LUKMAN HAKIM", jabatan: "ANGGOTA BPD", amount: 600000 },
    { name: "TURIMAN", jabatan: "ANGGOTA BPD", amount: 600000 },
];
